Repository xorbitsai/xoscar, pull requests merged in 2023-07, with the labels that each got.

#32 ENH: copy_to supports aio files
  .pre-commit-config.yaml
  python/xoscar/api.py
  python/xoscar/backends/context.py
  python/xoscar/backends/message.pyi
  python/xoscar/backends/message.pyx
  python/xoscar/backends/pool.py
  python/xoscar/backends/test/tests/test_transfer.py
  python/xoscar/context.pyx
  python/xoscar/core.pxd
  python/xoscar/core.pyx
Labels: enhancement

#37 BUG: Modify match words for catching error message
  python/xoscar/backends/indigen/pool.py
  python/xoscar/backends/pool.py
Labels: bug

#39 BUG: cannot import file_object_ref from xoscar directly
  python/xoscar/__init__.py
Labels: bug

#40 BUG: The bytes returned by cuda StreamReader may leads to deserialization failed
  python/xoscar/backends/communication/utils.py
Labels: bug, gpu

#41 ENH: Modify debug level
  python/xoscar/metrics/api.py
Labels: enhancement

#47 BUG: disable import cuda error when cpu only in a shared python env
  python/xoscar/_utils.pyx
Labels: bug, gpu

#49 Revert "BUG: disable import cuda error when cpu only in a shared python env"
  python/xoscar/_utils.pyx
Labels: gpu
