Repository xorbitsai/xoscar, pull requests merged in 2023-06, with the labels that each got.

#24 DOC: Add README.md
  README.md
  doc/source/architecture.png
Labels: documentation

#26 DOC: Update image
  README.md
  doc/source/architecture.png
Labels: documentation

#25 DOC: init
  .gitignore
  .readthedocs.yaml
  README.md
  doc/source/_static/architecture.png
  doc/source/_static/favicon.svg
  doc/source/conf.py
  doc/source/getting_started/index.rst
  doc/source/getting_started/installation.rst
  doc/source/getting_started/quickstart.rst
  doc/source/index.rst
  doc/source/reference/actor-pool.rst
  doc/source/reference/actor.rst
  doc/source/reference/index.rst
  doc/source/user_guide/actor-pool.rst
  doc/source/user_guide/actor.rst
  doc/source/user_guide/index.rst
  python/setup.cfg
  python/xoscar/api.py
Labels: documentation

#29 BLD: fix readthedocs
  doc/source/conf.py
Labels: build

#30 DOC: LLM inference
  doc/source/getting_started/index.rst
  doc/source/getting_started/llm-inference.rst
Labels: documentation, gpu

#23 FEAT: Support copy_to semantic, from buffer to buffer
  .github/workflows/python.yaml
  .pre-commit-config.yaml
  python/xoscar/__init__.py
  python/xoscar/api.py
  python/xoscar/backends/communication/ucx.py
  python/xoscar/backends/context.py
  python/xoscar/backends/core.py
  python/xoscar/backends/indigen/pool.py
  python/xoscar/backends/message.pyi
  python/xoscar/backends/message.pyx
  python/xoscar/backends/pool.py
  python/xoscar/backends/router.py
  python/xoscar/backends/test/pool.py
  python/xoscar/backends/test/tests/test_transfer.py
  python/xoscar/context.pyx
  python/xoscar/core.pxd
  python/xoscar/core.pyx
  python/xoscar/utils.py
Labels: feature
