Repository xorbitsai/xoscar, pull requests merged in 2023-09, with the labels that each got.

#72 BUG: Fix no_lock not work
  python/xoscar/core.pyx
  python/xoscar/tests/test_batch.py
Labels: bug

#74 ENH: fix versions of dependencies in toml
  python/pyproject.toml
Labels: enhancement

#54 FEAT: Add / remove a sub pool
  python/xoscar/backends/communication/socket.py
  python/xoscar/backends/config.py
  python/xoscar/backends/indigen/pool.py
  python/xoscar/backends/indigen/tests/test_pool.py
  python/xoscar/backends/test/pool.py
Labels: feature

#76 FEAT: Support fury
  .github/workflows/python.yaml
  python/xoscar/serialization/core.pyx
  python/xoscar/serialization/pyfury.py
  python/xoscar/serialization/tests/test_serial.py
Labels: feature

#77 BUG: append subpool logging
  python/xoscar/backends/indigen/pool.py
Labels: bug
