Repository xorbitsai/xoscar, pull requests merged in 2023-03, with the labels that each got.

#4 TST: introduce CI
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/other.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/codecov.yml
  .github/mergify.yml
  .github/workflows/assign.yaml
  .github/workflows/build-wheel.yaml
  .github/workflows/python.yaml
  .gitignore
  .pre-commit-config.yaml
  CI/conda-environment.yml
  CI/requirements-wheel.txt
  CI/test_functionality.py
  README.md
Labels: testing

#5 ENH: try to increase coverage
  .github/workflows/python.yaml
  python/setup.cfg
  python/xoscar/aio/__init__.py
  python/xoscar/aio/_runners.py
  python/xoscar/aio/isolation.py
  python/xoscar/backends/communication/tests/test_comm.py
Labels: enhancement

#6 ENH: separate ray
  .github/workflows/build-wheel.yaml
  .github/workflows/python.yaml
  python/pyproject.toml
  python/setup.cfg
  python/xoscar/__init__.py
  python/xoscar/backends/communication/base.py
  python/xoscar/backends/communication/dummy.py
  python/xoscar/backends/communication/socket.py
  python/xoscar/backends/communication/ucx.py
  python/xoscar/backends/pool.py
  python/xoscar/backends/ray/__init__.py
  python/xoscar/backends/ray/backend.py
  python/xoscar/backends/ray/communication.py
  python/xoscar/backends/ray/driver.py
  python/xoscar/backends/ray/pool.py
  python/xoscar/backends/ray/tests/__init__.py
  python/xoscar/backends/ray/tests/test_communication.py
  python/xoscar/backends/ray/tests/test_ray_actor_context.py
  python/xoscar/backends/ray/tests/test_ray_actor_driver.py
  python/xoscar/backends/ray/tests/test_ray_pool.py
  python/xoscar/backends/ray/tests/test_utils.py
  python/xoscar/backends/ray/utils.py
  python/xoscar/conftest.py
  python/xoscar/debug.py
  python/xoscar/metrics/api.py
  python/xoscar/metrics/backends/ray/__init__.py
  python/xoscar/metrics/backends/ray/ray_metric.py
  python/xoscar/metrics/backends/ray/tests/__init__.py
  python/xoscar/metrics/backends/ray/tests/test_ray_metric.py
  python/xoscar/metrics/tests/test_metric_api.py
  python/xoscar/serialization/__init__.py
  python/xoscar/serialization/ray.py
  python/xoscar/tests/core.py
Labels: enhancement

#8 BLD: fix build wheel
  .github/workflows/build-wheel.yaml
  CI/requirements-wheel.txt
  python/pyproject.toml
  python/setup.cfg
Labels: build

#10 ENH: remove subtask in profiling
  python/xoscar/profiling.py
  python/xoscar/tests/test_profiling.py
Labels: enhancement

#11 ENH: do not use global variable for profiling
  python/xoscar/backends/core.py
  python/xoscar/backends/message.pyx
  python/xoscar/profiling.py
Labels: enhancement

#12 TST: add tests for utils
  python/xoscar/tests/test_utils.py
  python/xoscar/utils.py
Labels: testing

#14 BUG: reorder import for init_extension_entrypoints
  python/xoscar/__init__.py
Labels: bug

#13 ENH: use /tmp/xoscar as default temp dir
  python/xoscar/backends/communication/socket.py
  python/xoscar/constants.py
Labels: enhancement
