Repository xorbitsai/xoscar, pull requests merged in 2023-08, with the labels that each got.

#57 ENH: add no_lock for avoiding possible dead lock during local actor ref method call
  python/xoscar/__init__.py
  python/xoscar/batch.py
  python/xoscar/core.pyx
  python/xoscar/tests/test_batch.py
Labels: enhancement

#58 ENH: Environment variable to set the Xoscar temp directory.
  python/xoscar/constants.py
Labels: enhancement

#60 TST: np.random.bytes with input float issue
  python/xoscar/backends/test/tests/test_transfer.py
Labels: testing

#64 BUG: Fix arrow serialization
  python/xoscar/serialization/__init__.py
  python/xoscar/serialization/arrow.py
Labels: bug

#62 BUG: fix xoscar installed by pypi not contains xoscar_pygloo.so
  .github/workflows/build-wheel.yaml
  CI/test_functionality.py
  cpp/CMakeLists.txt
  python/setup.py
Labels: bug

#56 FEAT:impl nccl interface for collective communication
  python/xoscar/collective/backend/nccl_backend.py
  python/xoscar/collective/common.py
  python/xoscar/collective/core.py
  python/xoscar/collective/process_group.py
  python/xoscar/collective/tests/test_nccl.py
  python/xoscar/collective/utils.py
Labels: feature

#66 BUG: Fix import error on Mac
  .github/workflows/build-wheel.yaml
  cpp/CMakeLists.txt
  python/xoscar/collective/common.py
  python/xoscar/collective/core.py
  python/xoscar/collective/process_group.py
  python/xoscar/collective/utils.py
Labels: bug

#71 DOC: Build from source
  README.md
Labels: documentation
