Repository xorbitsai/xoscar, pull requests merged in 2024-08, with the labels that each got.

#100 ENH: Fix socket channel config bug
  python/xoscar/backends/communication/socket.py
  python/xoscar/backends/indigen/tests/test_pool.py
Labels: enhancement, gpu

#102 BLD: Fix self-hosted CI env
  .github/workflows/python.yaml
  python/xoscar/serialization/tests/test_serial.py
Labels: build

#101 BUG: Fix route problem when listen on 0.0.0.0
  python/xoscar/backends/pool.py
  python/xoscar/utils.py
Labels: bug
