Repository xorbitsai/xoscar, pull requests merged in 2024-11, with the labels that each got.

#109 ENH: fix deprecation warning by pkgutil.find_loader
  python/xoscar/utils.py
Labels: enhancement

#111 ENH: Refine connection exception handling
  python/xoscar/backends/core.py
  python/xoscar/backends/pool.py
  python/xoscar/serialization/aio.py
Labels: enhancement

#112 FEAT: Add CONNECT_TIMEOUT option
  python/xoscar/backends/communication/socket.py
  python/xoscar/backends/indigen/tests/test_pool.py
  python/xoscar/constants.py
Labels: feature

#115 BUG: Fix leaking clients in actor caller
  python/xoscar/backends/communication/dummy.py
  python/xoscar/backends/communication/socket.py
  python/xoscar/backends/communication/ucx.py
  python/xoscar/backends/core.py
  python/xoscar/backends/test/tests/test_actor_context.py
Labels: bug

#116 BUG: Fix crash when exiting the daemon thread
  python/xoscar/backends/core.py
Labels: bug
