Repository xorbitsai/xoscar, pull requests merged in 2024-09, with the labels that each got.

#104 DOC: update sphinx to latest version
  .github/workflows/python.yaml
  python/setup.cfg
Labels: documentation

#105 BLD: macos arm64
  .github/workflows/build-wheel.yaml
Labels: build

#106 ENH: unpin "numpy<2.0" & move ucx-py to ucxx
  .github/workflows/python.yaml
  CI/conda-environment.yml
  CI/requirements-wheel.txt
  python/pyproject.toml
  python/setup.cfg
  python/xoscar/backends/communication/ucx.py
  python/xoscar/serialization/core.pyx
Labels: enhancement
