Repository xorbitsai/xoscar, pull requests merged in 2025-04, with the labels that each got.

#129 BUG: Fix upload pypi error
  .github/workflows/build-wheel.yaml
  CMakeLists.txt
  python/setup.py
Labels: bug

#128 FEAT: add virtual env support
  python/setup.cfg
  python/xoscar/virtualenv/__init__.py
  python/xoscar/virtualenv/core.py
  python/xoscar/virtualenv/tests/__init__.py
  python/xoscar/virtualenv/tests/test_uv.py
  python/xoscar/virtualenv/uv.py
Labels: feature

#131 ENH: just using parent's pipe for uv process
  python/xoscar/virtualenv/uv.py
Labels: enhancement

#133 ENH: support setting env on main pool
  python/xoscar/backends/indigen/pool.py
Labels: enhancement, gpu

#132 BUG: Fix ValueError when creating actor with class object as first argument
  .github/workflows/python.yaml
  python/xoscar/_utils.pyx
  python/xoscar/backends/indigen/tests/test_proxy.py
Labels: bug
