Repository xorbitsai/xoscar, pull requests merged in 2025-05, with the labels that each got.

#134 FEAT: Launch worker in venv
  .github/workflows/python.yaml
  CI/test_functionality.py
  python/pyproject.toml
  python/setup.cfg
  python/xoscar/backends/indigen/__main__.py
  python/xoscar/backends/indigen/fate_sharing.py
  python/xoscar/backends/indigen/pool.py
  python/xoscar/backends/indigen/shared_memory.py
  python/xoscar/backends/indigen/tests/test_debug.py
  python/xoscar/backends/indigen/tests/test_indigen_actor_context.py
  python/xoscar/backends/indigen/tests/test_pool.py
  python/xoscar/backends/indigen/tests/test_proxy.py
  python/xoscar/backends/pool.py
  python/xoscar/backends/test/pool.py
  python/xoscar/backends/test/tests/test_actor_context.py
  python/xoscar/backends/test/tests/test_transfer.py
  python/xoscar/collective/tests/test_nccl.py
  python/xoscar/virtualenv/core.py
  python/xoscar/virtualenv/tests/test_uv.py
  python/xoscar/virtualenv/uv.py
Labels: feature

#136 BLD: Fix build test
  .github/workflows/build-wheel.yaml
Labels: build

#138 BLD: Fix the check for ppid
  .github/workflows/build-wheel.yaml
  python/xoscar/backends/indigen/fate_sharing.py
  python/xoscar/backends/indigen/pool.py
  python/xoscar/backends/pool.py
Labels: build

#139 ENH: get_python_path() returns value when path exists
  python/xoscar/utils.py
  python/xoscar/virtualenv/core.py
  python/xoscar/virtualenv/uv.py
Labels: enhancement

#140 FEAT: added wait_for API
  python/xoscar/__init__.py
  python/xoscar/api.py
  python/xoscar/backends/indigen/tests/test_pool.py
Labels: feature

#141 FEAT: extended packages for virtualenv
  python/xoscar/virtualenv/core.py
  python/xoscar/virtualenv/uv.py
Labels: feature

#142 ENH: support specifying uv path via environment variable
  python/xoscar/virtualenv/uv.py
Labels: enhancement

#143 ENH: more logs
  python/xoscar/backends/indigen/pool.py
  python/xoscar/virtualenv/uv.py
Labels: enhancement

#144 ENH: specifying env when creating sub pool (before updating os.environ when sub pool created)
  .github/workflows/python.yaml
  python/pyproject.toml
  python/xoscar/backends/indigen/pool.py
Labels: enhancement

#145 ENH: [virtualenv] Support capturing log when installing packages
  python/xoscar/virtualenv/tests/test_utils.py
  python/xoscar/virtualenv/tests/test_uv.py
  python/xoscar/virtualenv/utils.py
  python/xoscar/virtualenv/uv.py
Labels: enhancement
